companieshouse/psc-verification-web

- src/app.ts
I've added to the path for `ch-node-utils/templates` because I think docker-chs-dev needs one path and e2e another.
> Adding to app views path for sake of e2e

- src/routers/handlers/start/start.ts
Not used and is pulling in typescript files into the js files in dist.
This may be the causes of e2e not deploying
> Removing an unused import 

- src/views/router_views/personal_code/personal_code.njk
I missed this when I added an id
> adding a missing comma that's causing template engine to error

- src/app.ts
- src/constants.ts
- src/routers/handlers/generic.ts
- src/routers/handlers/start/start.ts
- src/views/layouts/default.njk
- src/views/partials/__meta_header.njk
- src/views/partials/signout-bar.njk
- avoided display on start page by overriding `isSignedIn` in handler to false
IDVA3-1126
> Add user signout bar on all pages except start

- src/routers/handlers/confirmCompany/confirmCompany.ts
- src/services/external/companyProfileService.ts
- src/utils/session.ts
Should we be using the customer's Oauth2 token rather than API keys for the  API requests, at least to the public API's?
> CompanyProfile call - use Oauth2 token instead of API key

- src/routers/handlers/rle-director/rleDirector.ts
following changes to the folder naming, this path needs to be corrected to allow it to locate the template
re IDVA3-1250
> Fix the path for the RLE director template

- package-lock.json
- package.json
- src/routers/confirmCompanyRouter.ts
- src/services/pscService.ts
- test/mocks/Psc.mock.ts
- test/services/pscService.unit.ts
- in the confirmCompany Router I've hard coded a value for a PSC individual in our Docker `company_pscs` collection, that can then be retrieved with this new service
- the service can be called with `const pscDetailsResponse = await getPscIndividual(req, "00006400", "1kdaTltWeaP1EB70SSD9SLmiK5Y");`
IDVA3-1491
> Add PSC service to call getPscIndividual details

- src/services/pscService.ts
- test/mocks/psc.mock.ts
- test/services/pscService.unit.ts
- replacing `PersonWithSignificantControlResource` with `PersonWithSignificantControl` 
- this is what the sdk does send back - https://github.com/companieshouse/api-sdk-node/blob/master/src/services/psc/service.ts#L18
> Correcting the type returned form SDK and fixing the test

- src/routers/handlers/new-submission/newSubmissionHandler.ts
- src/routers/handlers/personal-code/personalCode.ts
- src/routers/handlers/psc-type/pscType.ts
- src/routers/individualPscListRouter.ts
- src/routers/individualStatementRouter.ts
- src/routers/personalCodeRouter.ts
- src/routers/pscTypeRouter.ts
- test/routers/handlers/individual-statement/individualStatement.int.ts
- test/routers/handlers/new-submission/newSubmissionHandler.int.ts
- Set the transaction id, submission id and lang values correctly and pass them around so that language switching works
- can go back and forth between languages on each page
- can progress through journey and retain language
- language retained from the links on the Confirmation page too
- unit tests
IDVA3-1499
IDVA3-1189 - no change done for this, but please see my comment on the story.
> Defect fix - Transaction ID and Submission ID lost from path

- src/views/partials/__meta_header.njk
> Replace favicon with version in govuk v4.6.0

- src/services/transactionService.ts
- test/mocks/transaction.mock.ts
- test/services/transactionService.unit.ts
Company Number not allowed for a User Transaction, but the name will get passed to the Confirmation Email 
IDVA3-1566
```
{
"_id" : "094785-968417-186120",
"data" : {
"_id" : "094785-968417-186120",
"company_name" : "THE GIRLS' DAY SCHOOL TRUST",
"created_at" : ISODate("2024-06-17T08:14:55.000Z"),
"created_by" : {
"language" : "en",
"id" : "Y2VkZWVlMzhlZWFjY2M4MzQ3MT",
"email" : "demo@ch.gov.uk"
},
"updated_at" : ISODate("2024-06-17T08:14:55.000Z"),
"description" : "PSC Verification Transaction",
"etag" : "aea61aad1995657c8856770e8bbc4b2376aa100f",
"links" : {
"self" : "/transactions/094785-968417-186120"
},
"reference" : "PscVerificationReference",
"resources" : {
"/transactions/094785-968417-186120/persons-with-significant-control-verification/666ff081c59a4550ef024cf7" : {
```
> Pass company Name in Transaction Resource.  

- src/routers/handlers/start/startHandler.ts
- test/routers/handlers/start/start.unit.ts
- title value passed in View data not used in template, so removing
- the 2nd test wasn't actually checking anything, so fixing that and simplifying the test
> Simplify start test and make it actually check the view data returned

- src/routers/handlers/psc-type/pscTypeHandler.ts
- rename a function parameter to avoid shadowing 'companyNumber' variable
> Fix sonar issue 'shadowed variable'

- src/app.ts
- src/config/index.ts
- src/middleware/serviceLive.ts
- src/views/router_views/serviceNotLive/serviceNotLive.njk
- test/app.int.ts
- test/global.setup.ts
This is not the Service Maintenance functionality based on a call to the API.  Rather it is a block to any use until the service is 'live and available to customers'
Config PR's:
- https://github.com/companieshouse/docker-chs-development/pull/1266
- https://github.com/companieshouse/ecs-service-configs-dev/pull/535
IDVA3-1853
> Add page for Service not live based on config flag

- src/routers/handlers/stop-screen/stopScreenHandler.ts
- test/routers/handlers/stop-screen/stopScreenHandler.unit.ts
This is to fix a bug, where the company number param was lost from the Url when toggling the language links
IDVA3-2522
> Add the company number param to the current Url 

- locales/cy/stop-screens.json
- locales/en/stop-screens.json
- package.json
- src/constants.ts
- src/routers/handlers/stop-screen/stopScreenHandler.ts
- src/views/router_views/stop_screen/company-status.njk
- test/routers/handlers/stop-screen/stopScreen.int.ts
- test/routers/handlers/stop-screen/stopScreenHandler.unit.ts
Standard stop screen - template and control, but not the validation/navigation to it yet, which is a later story
> [!NOTE]  
> I've added the `/locales` directory to the nodemon config - good idea?
IDVA3-2458
> Add template and handling for company status stop screen

- src/app.ts
- src/routers/handlers/start/startHandler.ts
- src/routers/startRouter.ts
- test/app.errors.int.ts
- test/routers/handlers/start/start.unit.ts
- move app.ts error handling code after routerDispatch call
- add integration tests for errors
- default export StartHandler (easier mocking)
> Improve handling unexpected errors

- src/constants.ts
- src/routers/handlers/individual-psc-list/individualPscListHandler.ts
- src/routers/individualPscListRouter.ts
- src/services/companyPscService.ts
- test/mocks/companyPsc.mock.ts
- test/mocks/psc.mock.ts
- test/routers/handlers/individual-psc-list/individualPscListHandler.unit.ts
- test/routers/individualPscListRouter.int.ts
- test/services/companyPscService.unit.ts
- avoid using middleware validation:
- no second company PSC data fetch in handler
- and no need to store PSC data in res.locals (potentially much and sensitive)
- check for exclusively super secure in the handler, set an exclusivity flag
- use that flag in router to either route to the appropriate stop screen, or render the PSC list screen
> Add exclusively super secure stop screen validation/routing

- src/views/router_views/personalCode/personal-code.njk
To test these changes it may be necessary to first pull the latest CDN image with `docker pull 169942020521.dkr.ecr.eu-west-2.amazonaws.com/local/cdn.ch.gov.uk`.
[IDVA3-2466]: https://companieshouse.atlassian.net/browse/IDVA3-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IDVA3-2466 Ensure correct formatting is used for the personal code field

- locales/cy/stop-screens.json
- locales/en/stop-screens.json
- src/constants.ts
- src/routers/handlers/individual-psc-list/individualPscListHandler.ts
- src/routers/handlers/stop-screen/stopScreenHandler.ts
- src/routers/individualPscListRouter.ts
- src/views/router_views/stopScreen/empty-psc-list.njk
- test/mocks/companyPsc.mock.ts
- test/routers/handlers/stop-screen/stopScreen.int.ts
- test/routers/handlers/stop-screen/stopScreenHandler.unit.ts
- test/routers/individualPscListRouter.int.ts
I wanted to use `it.each` for the Jest tests since they're largely the same, but I ran into an issue where `it.each` is causing a timeout every time. I've asked Simon for help.
[IDVA3-2629]: https://companieshouse.atlassian.net/browse/IDVA3-2629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IDVA3-2629 Insert message on psc-list screen for no individual PSC scenario

- src/constants.ts
- src/views/router_views/error/internal-server-error.njk
- src/views/router_views/error/page-not-found.njk
- src/views/router_views/name_mismatch/name_mismatch.njk
- src/views/router_views/serviceUnavailable/service-unavailable.njk
- src/views/router_views/stopScreen/company-status.njk
- src/views/router_views/stopScreen/company-type.njk
- src/views/router_views/stopScreen/empty-psc-list.njk
- src/views/router_views/stopScreen/psc-dob-mismatch.njk
- src/views/router_views/stopScreen/super-secure.njk
Testing involves going to each route, clicking the updated links, and checking their events fire correctly on the [Matomo dashboard](https://matomo.platform.aws.chdev.org/index.php?module=CoreHome&action=index&idSite=24&period=day&date=today&updated=1#?idSite=24&period=day&date=today&category=Dashboard_Dashboard&subcategory=1&segment=pageUrl%3D@persons-with-significant-control) (you may need to adjust the date range).
[IDVA3-2572]: https://companieshouse.atlassian.net/browse/IDVA3-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  IDVA3-2572 Matomo tracking for cloudy day screens

- locales/en/individual-statement.json
- test/routers/handlers/individual-statement/individualStatement.int.ts
Only a small change to localised strings & altered tests.
[IDVA3-2783]: https://companieshouse.atlassian.net/browse/IDVA3-2783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IDVA3-2783 Update wording in psc-statement screen

- package-lock.json
- package.json
- src/config/index.ts
- src/routers/handlers/individual-psc-list/individualPscListHandler.ts
- src/routers/handlers/individual-statement/individualStatementHandler.ts
- src/routers/handlers/name-mismatch/nameMismatchHandler.ts
- src/routers/handlers/personal-code/personalCodeHandler.ts
- src/routers/handlers/psc-verified/pscVerifiedHandler.ts
- src/services/apiClientService.ts
- src/services/pscService.ts
- test/middleware/checkCompany.int.ts
- test/mocks/psc.mock.ts
- test/routers/handlers/individual-psc-list/individualPscListHandler.int.ts
- test/routers/handlers/individual-psc-list/individualPscListHandler.unit.ts
- test/routers/handlers/psc-verified/pscVerified.int.ts
- test/routers/handlers/psc-verified/pscVerifiedHandler.unit.ts
- test/routers/individualPscListRouter.int.ts
- test/services/apiClientService.unit.ts
- test/services/pscService.unit.ts
The PSC service was updated to retrieve an individual PSC with their verification state. 
Config was updated to reference the CHS_INTERNAL_API_KEY in the API client service.
**Notes**
- A temporary block of code has been added to `individualPscListHandler.ts` which may be used to view the verification state in debug mode when running locally in Docker.
- `package-lock.json` has been temporarily update to reference the `api-sdk-node` changes in [PR #764](https://github.com/companieshouse/api-sdk-node/pull/764), and will be reverted following review
> IDVA3-2470 Add get psc verification state endpoint

- src/app.ts
- src/constants.ts
- src/lib/errors/httpError.ts
- src/middleware/blockClosedTransaction.ts
- src/services/transactionService.ts
- test/authentication/authenticationCheck.int.ts
- test/middleware/blockClosedTransaction.unit.ts
- test/routers/handlers/individual-statement/individualStatement.int.ts
- test/routers/handlers/name-mismatch/nameMismatch.int.ts
- test/routers/handlers/personal-code/personalCode.int.ts
- test/routers/handlers/stop-screen/stopScreen.int.ts
- test/routers/individualStatementRouter.int.ts
- test/routers/stopScreenRouter.int.ts
- test/services/transactionService.unit.ts
Jira ticket: https://companieshouse.atlassian.net/browse/IDVA3-2997
Notes:
* Ensure that the PSC you're testing with is able to verify (i.e. no validation errors), otherwise the transaction won't close when you reach the `psc-verified` screen.
* Quite a few tests had to be tweaked to mock an open transaction so that tests don't get blocked when trying to access transaction-related screens. All these tests can be seen in [this commit](https://github.com/companieshouse/psc-verification-web/pull/234/commits/0dac735c04a3958ef7deefacbdaa1bb3ebfb7dbc).
Testing involves going through the journey, making duplicates of each tab as you progress until you get to `psc-verified`, then going back to each screen and refreshing. Any transaction related screens (`personal-code`, `individual-statement`) …
> IDVA3-2997 Block transaction-related screens if the transaction is closed

- src/app.ts
- src/lib/errors/dataIntegrityError.ts
- src/middleware/error-interceptors/dataIntegrityErrorInterceptor.ts
- src/routers/handlers/generic.ts
- src/routers/handlers/stop-screen/stopScreenHandler.ts
- src/services/pscVerificationService.ts
- test/middleware/error-interceptors/dataIntegrityErrorInterceptor.unit.ts
- test/routers/handlers/stop-screen/stopScreen.int.ts
- test/routers/handlers/stop-screen/stopScreenHandler.unit.ts
- test/services/pscVerificationService.unit.ts
Jira ticket: https://companieshouse.atlassian.net/browse/IDVA3-2858
Notes:
- The `backUrl` was removed from "problem with PSC data" stop screen since the stop screen can now in more than one point along the web journey. 
- The ticket mentions two etag scenarios but I was unable to find any API error response for them in psc-verification-api. After some discussion we decided to remove the two scenarios from the ticket ACs.
- On top of specific error scenarios being handled differently in `pscVerificationService.ts`, I also rewrote every `createAndLogError()` into its basic error equivalent for consistency. Thrown Errors are automatically logged by interceptors now.
> IDVA3-2858 Handle data integrity validation errors

- src/middleware/error-interceptors/httpErrorInterceptor.ts
- src/routers/handlers/psc-verified/pscVerifiedHandler.ts
- test/routers/handlers/psc-verified/pscVerifiedHandler.unit.ts
**Jira ticket**: [IDVA3-3094](https://companieshouse.atlassian.net/browse/IDVA3-3094)
Previously we had just logged an error if the `closeTransaction` call failed for any reason. This PR introduces an error that will be presented to the user as a 500 internal server error.
>
```logs
2025-06-11T10:30:26.732+00:00 error: pscVerifiedHandler - Generic error at URL: /persons-with-significant-control-verification/transaction/001932-836617-496377/submission/68495a92d70d7051e822af48/psc-verified?companyNumber=00006400&lang=en. Error: failed to close transaction for transactionId="001932-836617-49637766", submissionId="68495a92d70d7051e822af48"
at /app/src/routers/handlers/psc-verified/pscVerifiedHandler.ts:63:23
at processTicksAndRejections …
```
> IDVA3-3094 Handle error scenario for closing a transaction

- locales/cy/errors.json
- locales/cy/personal-code.json
- locales/cy/start.json
- locales/en/errors.json
**IDVA3-1108**
- I've used unicode notation for the special welsh characters
- also includes additions for errors and main service title
- the 2 keys `default_error_summary` and `default_error_inline` - I don't see being used anywhere, so removed
> Welsh text for personal code screen

- locales/cy/personal-code.json
**Jira ticket**: part of IDVA3-1108
>
> Add a space at end of word, which matches the english value

- locales/cy/global.json
- locales/en/global.json
- package-lock.json
- src/app.ts
- src/config/index.ts
- src/views/layouts/default.njk
- src/views/partials/__footer.njk
- src/views/partials/__meta_header.njk
- src/views/partials/signout-bar.njk
- test/global.setup.ts
**Jira ticket**: IDVA3-2613
Requires: https://github.com/companieshouse/docker-chs-development/pull/1825
> Replace the nav bar with the version in ch-node-utils

- locales/cy/individual-statement.json
- locales/cy/start.json
**Jira ticket**: IDVA3-1109 & IDVA3-3292
- add welsh language values for statement screen
- also fixed the 'a caret' letter in the top banner
> Add welsh language values for statement screen

- locales/cy/individual-statement.json
- locales/en/individual-statement.json
**Jira ticket**: IDVA3-3320
- replace unicode values
- remove unused key
> Correct the key/values for welsh that had been mixed up

- locales/cy/global.json
- locales/en/global.json
- src/views/layouts/default.njk
- src/views/layouts/shell.njk
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3307
Adding welsh translation for skip content link.
Toggle to Welsh.
Place cursor over the web browser url.
Press tab.
> Adding welsh translation for skip content link

- src/middleware/error-interceptors/httpErrorInterceptor.ts
- src/routers/handlers/generic.ts
- test/middleware/error-interceptors/httpErrorInterceptor.unit.ts
- test/routers/handlers/generic.unit.ts
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3322
The bug seems to be caused by a view being displayed without setting the bits of viewData that routers & handlers add by default (specifically userEmail). Without this, Nunjucks seems to fall through to whatever email was rendered last, which is a serious flaw. This PR fixes the issue, but we ought to investigate further into how Nunjucks caches information like this.
The key change is that the viewData populating functionality was extracted out of GenericHandler so it can also be used by error interceptors and non router/handler constructs like middleware.
>
The screenshot above shows two browsers, one in private mode. The one on the left is `demo@ch.gov.uk` …
> IDVA3-3322 Fix cross-session email data leak

- src/app.ts
**Jira ticket**: None
Hardcodes the govuk frontend version due to an issue where `getGOVUKFrontendVersion` expects `package.json` to be present in ECS (which isn't the case for psc-verification-web). Should unblock `cidev-apply`.
> Quick fix: hardcode govuk-frontend version

- Makefile
- src/app.ts
**Jira ticket**: N/a
Prevents our Makefile build step from removing `package.json` to hopefully fix ECS falling over due to `getGOVUKFrontendVersion()` expecting `package.json` to be present.
>
Results will be whether the cidev-apply task finishes successfully.
>
N/a
> Revert hardcoded govuk frontend version & attempt fix via Makefile

- src/views/partials/error-summary.njk
- src/views/router_views/personalCode/personal-code.njk
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3396
Fixes a regression due to the rebrand where the error-summary.njk template had an additional layout div.
>
>
Included in Jira.
> IDVA3-3396 Fix broken error-summary layout

- package-lock.json
- package.json
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3385
Bumps api-sdk-node to use the latest IDV endpoint changes from [IDVA3-3579 (removal of oracle-query-api call)](https://companieshouse.atlassian.net/browse/IDVA3-3579).
>
>
Test notes for testers will differ due to environments. For devs:
1. Ensure you've pulled the latest docker-chs-development.
2. Stop all running services.
3. Delete the mongo volume: `docker volume rm docker-chs-development_mongo_data`.
4. `chs-dev up` and check the psc-list screen to confirm dates are populating correctly.
> IDVA3-3385 Update web to use data retrieved from public endpoint

- src/views/router_views/personalCode/personal-code.njk
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3558
Add missing label to personal code form.
Check no warning appears on personal code input box.
> Add missing label to personal code form.

- src/constants.ts
- src/routers/handlers/individual-psc-list/individualPscListHandler.ts
- src/views/router_views/individualPscList/individual-psc-list.njk
- test/routers/handlers/individual-psc-list/individualPscListHandler.int.ts
- test/routers/handlers/individual-psc-list/individualPscListHandler.unit.ts
**Jira ticket**: https://companieshouse.atlassian.net/browse/IDVA3-3456
Adds request extension URLs in the specified format to PSCs in the psc-list screen. Note that only PSCs that can verify are given the option to request an extension, so only they will have a link generated. Matomo was one of the ACs but it's already in-place.
>
>
Included in Jira ticket.
> IDVA3-3456 Add "request extension" URLs to PSC list
